create Inputs.js file, add selector "create"
JuliaLobanova/MLH20704 pull request #2
Opened 2020-11-09 20:57 UTC by Ekatim

2020-11-09 23:40 UTC, JuliaLobanova commented on data/selectors.json
> +  "create": ".ant-btn"
This selector exists as "SubmitBtn" on line 16. Please delete your changes.

2020-11-09 23:41 UTC, JuliaLobanova requested changes

2020-11-09 23:41 UTC, JuliaLobanova commented on data/selectors.json
> +  "tryAgainBtn": ".btn-primary",
This selector exists as "SubmitBtn" on line 16. Please delete your changes.

2020-11-10 04:32 UTC, Sovestdp approved these changes

2020-11-10 21:01 UTC, JuliaLobanova approved these changes

2020-11-10 21:03 UTC, merged