MLH-617 TC-040 create
JuliaLobanova/MLH20704 pull request #33
Opened 2020-11-19 19:19 UTC by Beligma

2020-11-19 19:24 UTC, Ekatim approved these changes

2020-11-19 21:45 UTC, JuliaLobanova commented on test/regression/image.js
> +            const input = $(sel.imageDownload);
Please replace lines 44-50 with helper imageDownload. Do not duplicate code)))

2020-11-19 21:46 UTC, JuliaLobanova requested changes
Please replace lines 44-50 with helper imageDownload. Do not duplicate code)))

2020-11-20 02:38 UTC, JuliaLobanova approved these changes

2020-11-20 02:39 UTC, ivansh83 approved these changes

2020-11-20 02:40 UTC, Ekatim approved these changes

2020-11-20 02:40 UTC, Linaris1993 approved these changes

2020-11-20 02:40 UTC, merged